#!/usr/bin/env python3
"""Generate the paper's tables, macros, and figures from committed evidence.

Same discipline as the agent-go paper: every result number in the LaTeX
comes from generated/, built here from docs/paper/data/. No hand-typed
statistics. Run from this directory or via the Makefile `generated` target.

Inputs (committed):
  data/stage0/{vanilla,diff}-seedN-metrics.jsonl   seed band runs (seeds 1-4)
  data/stage0/recorded-seed0.json                  recorded original seed 0
  data/stage1/{vanilla,diff}-metrics.jsonl         the headline Stage 1 pair
  data/position_binned_nll.npz                     per-position held-out NLL

Outputs (generated/):
  summary_macros.tex   \newcommand macros the prose cites
  stage0_table.tex     per-seed paired deltas
  stage1_table.tex     train/val endpoints
  posbin_table.tex     position-binned NLL
  stage0_band.tex      pgfplots: delta per seed with zero line
  stage1_curves.tex    pgfplots: train curves + val points, both variants
  posbin_fig.tex       pgfplots: delta by position bin
"""
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
OUT = HERE / "generated"

SEEDS = [1, 2, 3, 4]
GEN_HEADER = "% GENERATED by gen.py. Do not edit.\n"


def read_metrics(path):
    recs = []
    with open(path) as f:
        for line in f:
            recs.append(json.loads(line))
    return recs


def last_val(recs):
    v = None
    for r in recs:
        if "val_loss_full" in r:
            v = r["val_loss_full"]
    return v


def val_at(recs, step):
    for r in recs:
        if r.get("step") == step and "val_loss_full" in r:
            return r["val_loss_full"]
    return None


def train_tail_mean(recs, n=1000):
    steps = [r["train_loss"] for r in recs if "train_loss" in r]
    return float(np.mean(steps[-n:]))


def fmt(x, nd=3):
    return f"{x:.{nd}f}"


def sfmt(x, nd=3):
    return f"{x:+.{nd}f}"


def main():
    OUT.mkdir(exist_ok=True)

    # Stage 0 seed band.
    band = []  # (seed, vanilla, diff, delta)
    for s in SEEDS:
        va = last_val(read_metrics(DATA / f"stage0/vanilla-seed{s}-metrics.jsonl"))
        di = last_val(read_metrics(DATA / f"stage0/diff-seed{s}-metrics.jsonl"))
        band.append((s, va, di, di - va))
    deltas = np.array([d for _, _, _, d in band])
    rec = json.loads((DATA / "stage0/recorded-seed0.json").read_text())
    rec_delta = rec["diff_val_full"] - rec["vanilla_val_full"]
    flips = sum(1 for d in deltas if np.sign(d) != np.sign(np.mean(deltas)))

    # Stage 1.
    s1v = read_metrics(DATA / "stage1/vanilla-metrics.jsonl")
    s1d = read_metrics(DATA / "stage1/diff-metrics.jsonl")
    s1 = {
        "van_val": last_val(s1v),
        "diff_val": last_val(s1d),
        "van_train": train_tail_mean(s1v),
        "diff_train": train_tail_mean(s1d),
        "van_val25": val_at(s1v, 25000),
        "diff_val25": val_at(s1d, 25000),
    }
    s1["val_delta"] = s1["diff_val"] - s1["van_val"]
    s1["train_delta"] = s1["diff_train"] - s1["van_train"]

    # Position-binned held-out NLL, 8 bins of 256.
    z = np.load(DATA / "position_binned_nll.npz")
    nbins, width = 8, 256
    bins = []
    for b in range(nbins):
        lo, hi = b * width, (b + 1) * width
        bd = float(z["diff"][lo:hi].mean())
        bv = float(z["vanilla"][lo:hi].mean())
        bins.append((lo, hi - 1, bd, bv, bd - bv))
    overall_d = float(z["diff"].mean())
    overall_v = float(z["vanilla"].mean())
    bin_deltas = [d for *_, d in bins]

    # Macros.
    m = [GEN_HEADER]

    def macro(name, val):
        m.append(f"\\newcommand{{\\{name}}}{{{val}}}\n")

    macro("StageZeroMeanDelta", sfmt(float(deltas.mean())))
    macro("StageZeroStdDelta", fmt(float(deltas.std(ddof=1))))
    macro("StageZeroMinDelta", sfmt(float(deltas.min())))
    macro("StageZeroMaxDelta", sfmt(float(deltas.max())))
    macro("StageZeroFlipCount", str(flips))
    macro("StageZeroSeedCount", str(len(SEEDS)))
    macro("StageZeroRecordedDelta", sfmt(rec_delta))
    macro("StageOneValDeltaSigned", sfmt(s1["val_delta"]))
    macro("StageOneTrainDeltaSigned", sfmt(s1["train_delta"]))
    macro("StageOneVanillaVal", fmt(s1["van_val"]))
    macro("StageOneDiffVal", fmt(s1["diff_val"]))
    macro("StageOneVanillaTrain", fmt(s1["van_train"]))
    macro("StageOneDiffTrain", fmt(s1["diff_train"]))
    macro("StageOneDiffValLateRise", f"{fmt(s1['diff_val25'])} to {fmt(s1['diff_val'])}")
    macro("StageOneVanillaValLateFall", f"{fmt(s1['van_val25'])} to {fmt(s1['van_val'])}")
    macro("PosbinOverallDelta", sfmt(overall_d - overall_v))
    macro("PosbinMinDelta", sfmt(min(bin_deltas)))
    macro("PosbinMaxDelta", sfmt(max(bin_deltas)))
    macro("PosbinLastBinDelta", sfmt(bins[-1][4]))
    (OUT / "summary_macros.tex").write_text("".join(m))

    # Stage 0 table.
    t = [GEN_HEADER, "\\begin{tabular}{rrrr}\n\\toprule\n",
         "seed & vanilla & diff & $\\delta$ \\\\\n\\midrule\n",
         f"0 (recorded) & {fmt(rec['vanilla_val_full'])} & {fmt(rec['diff_val_full'])} & {sfmt(rec_delta)} \\\\\n"]
    for s, va, di, d in band:
        t.append(f"{s} & {fmt(va)} & {fmt(di)} & {sfmt(d)} \\\\\n")
    t.append("\\bottomrule\n\\end{tabular}\n")
    (OUT / "stage0_table.tex").write_text("".join(t))

    # Stage 1 table.
    t = [GEN_HEADER, "\\begin{tabular}{lrrr}\n\\toprule\n",
         "metric & diff & vanilla & $\\delta$ \\\\\n\\midrule\n",
         f"final train loss (last 1000-step mean) & {fmt(s1['diff_train'])} & {fmt(s1['van_train'])} & {sfmt(s1['train_delta'])} \\\\\n",
         f"held-out val loss at step 30000 & {fmt(s1['diff_val'])} & {fmt(s1['van_val'])} & {sfmt(s1['val_delta'])} \\\\\n",
         "\\bottomrule\n\\end{tabular}\n"]
    (OUT / "stage1_table.tex").write_text("".join(t))

    # Position-binned table.
    t = [GEN_HEADER, "\\begin{tabular}{lrrr}\n\\toprule\n",
         "position & diff & vanilla & $\\delta$ \\\\\n\\midrule\n"]
    for lo, hi, bd, bv, d in bins:
        t.append(f"{lo}--{hi} & {fmt(bd)} & {fmt(bv)} & {sfmt(d)} \\\\\n")
    t.append(f"\\midrule\noverall & {fmt(overall_d)} & {fmt(overall_v)} & {sfmt(overall_d - overall_v)} \\\\\n")
    t.append("\\bottomrule\n\\end{tabular}\n")
    (OUT / "posbin_table.tex").write_text("".join(t))

    # Figure: stage 0 band, delta per seed, zero line.
    f = [GEN_HEADER, "\\begin{tikzpicture}\n\\begin{axis}[\n",
         "  width=\\linewidth, height=5cm, ylabel={paired $\\delta$ (nats)},\n",
         "  xlabel={seed}, xtick={0,1,2,3,4}, only marks,\n",
         "  ymajorgrids, tick label style={font=\\small},\n]\n",
         "\\addplot+[mark=*, mark size=2.5pt] coordinates {",
         f"(0,{rec_delta:.4f}) "]
    f += [f"({s},{d:.4f}) " for s, _, _, d in band]
    f += ["};\n\\addplot[domain=-0.5:4.5, samples=2, dashed] {0};\n",
          "\\end{axis}\n\\end{tikzpicture}\n"]
    (OUT / "stage0_band.tex").write_text("".join(f))

    # Figure: stage 1 train curves (downsampled) + val points.
    def series(recs, key, every=1):
        pts = [(r["step"], r[key]) for r in recs if key in r]
        return pts[::every]

    def coords(pts, start=2000):
        return " ".join(f"({s},{v:.4f})" for s, v in pts if s >= start)

    f = [GEN_HEADER, "\\begin{tikzpicture}\n\\begin{axis}[\n",
         "  width=\\linewidth, height=6cm, xlabel={step}, ylabel={loss (nats)},\n",
         "  legend style={at={(0.5,1.04)},anchor=south,legend columns=-1,draw=none},\n",
         "  ymajorgrids, tick label style={font=\\small},\n]\n"]
    f.append("\\addplot+[no marks, thin] coordinates {"
             + coords(series(s1d, "train_loss", every=100)) + "};\n")
    f.append("\\addplot+[no marks, thin] coordinates {"
             + coords(series(s1v, "train_loss", every=100)) + "};\n")
    f.append("\\addplot+[mark=*, thick] coordinates {"
             + coords(series(s1d, "val_loss_full")) + "};\n")
    f.append("\\addplot+[mark=square*, thick] coordinates {"
             + coords(series(s1v, "val_loss_full")) + "};\n")
    f.append("\\legend{diff train, vanilla train, diff val, vanilla val}\n")
    f.append("\\end{axis}\n\\end{tikzpicture}\n")
    (OUT / "stage1_curves.tex").write_text("".join(f))

    # Figure: position-binned delta.
    f = [GEN_HEADER, "\\begin{tikzpicture}\n\\begin{axis}[\n",
         "  width=\\linewidth, height=5cm, ylabel={$\\delta$ NLL (nats)},\n",
         "  xlabel={token position (bin start)},\n",
         "  ymajorgrids, tick label style={font=\\small},\n]\n",
         "\\addplot+[mark=*] coordinates {"]
    f += [f"({lo},{d:.4f}) " for lo, hi, bd, bv, d in bins]
    f += ["};\n\\addplot[domain=0:2048, samples=2, dashed] {0};\n",
          "\\end{axis}\n\\end{tikzpicture}\n"]
    (OUT / "posbin_fig.tex").write_text("".join(f))

    print(f"generated {len(list(OUT.glob('*.tex')))} files in {OUT}")


if __name__ == "__main__":
    main()
