"""Cross-check the PyTorch DiffAttention against the same vendored
microsoft/unilm fixture the MLX side uses.

The fixture (`../../data/ref_fixtures/diffattn_toy_v1.npz`) was generated by
running the vendored PyTorch reference on a deterministic input. Both this
port and the MLX implementation must match it to within design §7.4
tolerance.

Tolerance: 1e-3 (fp32). On CPU this is easy; on CUDA we disable TF32 so
matmul uses IEEE fp32 and the test stays strict.
"""
from pathlib import Path

import numpy as np
import pytest
import torch

from model import DiffAttention

FIXTURE = Path(__file__).resolve().parent.parent.parent / "data" / "ref_fixtures" / "diffattn_toy_v1.npz"


def _disable_tf32():
    """Force strict IEEE fp32 matmul on CUDA, matching CPU behavior."""
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False


@pytest.mark.parametrize("device", [
    pytest.param("cpu"),
    pytest.param("cuda", marks=pytest.mark.skipif(
        not torch.cuda.is_available(), reason="no CUDA"
    )),
])
def test_pytorch_diff_attention_matches_microsoft_reference(device):
    if not FIXTURE.exists():
        pytest.skip(f"fixture missing: {FIXTURE}. Run scripts/generate_ref_fixture.py once on the Mac.")

    if device == "cuda":
        _disable_tf32()

    data = np.load(FIXTURE)
    DIM = int(data["dim"])
    NUM_HEADS_REF = int(data["num_heads_ref"])

    # Reference's num_heads = our n_heads_diff. So n_heads_vanilla = 2 * NUM_HEADS_REF.
    n_heads_vanilla = NUM_HEADS_REF * 2
    qk_head_dim = DIM // n_heads_vanilla

    input_x = torch.from_numpy(data["input_x"].astype(np.float32)).to(device)
    expected_out = data["ref_output"].astype(np.float32)

    # Build module (layer_idx=1 so lambda_init=0.2, matching reference depth=0).
    attn = DiffAttention(
        dim=DIM,
        n_heads_vanilla=n_heads_vanilla,
        qk_head_dim=qk_head_dim,
        layer_idx=1,
    ).to(device)

    # Copy weights from fixture into PyTorch module.
    # MLX and PyTorch both use (out, in) for Linear.weight, so direct copy.
    with torch.no_grad():
        attn.q_proj.weight.copy_(torch.from_numpy(data["weight__q_proj__weight"].astype(np.float32)))
        attn.k_proj.weight.copy_(torch.from_numpy(data["weight__k_proj__weight"].astype(np.float32)))
        attn.v_proj.weight.copy_(torch.from_numpy(data["weight__v_proj__weight"].astype(np.float32)))
        attn.o_proj.weight.copy_(torch.from_numpy(data["weight__out_proj__weight"].astype(np.float32)))
        attn.lambda_q1.copy_(torch.from_numpy(data["weight__lambda_q1"].astype(np.float32)))
        attn.lambda_k1.copy_(torch.from_numpy(data["weight__lambda_k1"].astype(np.float32)))
        attn.lambda_q2.copy_(torch.from_numpy(data["weight__lambda_q2"].astype(np.float32)))
        attn.lambda_k2.copy_(torch.from_numpy(data["weight__lambda_k2"].astype(np.float32)))
        attn.subln.scale.copy_(torch.from_numpy(data["weight__subln__weight"].astype(np.float32)))

    attn.eval()
    with torch.no_grad():
        actual = attn(input_x)
    actual_np = actual.detach().cpu().numpy().astype(np.float32)

    max_diff = float(np.abs(actual_np - expected_out).max())
    mean_diff = float(np.abs(actual_np - expected_out).mean())
    assert max_diff < 1e-3, (
        f"[{device}] max |diff| = {max_diff:.3e} (mean |diff| = {mean_diff:.3e}); "
        f"expected < 1e-3 per design §7.4. "
        f"actual stats: mean={actual_np.mean():.4f} std={actual_np.std():.4f}; "
        f"expected stats: mean={expected_out.mean():.4f} std={expected_out.std():.4f}"
    )
